# Generated by Django 4.2.5 on 2023-09-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testresult', '0001_initial'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question.question')),
                ('testResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testresults', to='testresult.testresult')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
