# Generated by Django 4.2.5 on 2023-09-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('correctAnswer', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_question', to='test.test')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
